name: Detect Prohibited Applications Spawning cmd exe
id: c10a18cb-fd80-4ffa-a844-25026e0a0c94
version: 6
date: '2022-03-01'
author: Ignacio Bermudez Corrales, Splunk
status: production
type: Anomaly
description: The following analytic identifies parent processes, browsers, Windows
  terminal applications, Office Products and Java spawning cmd.exe. By its very nature,
  many applications spawn cmd.exe natively or built into macros. Much of this will
  need to be tuned to further enhance the risk.
data_source:
- Windows Security 4688
search:
  selection1:
    actor.process.file.name:
    - winword.exe
    - excel.exe
    - outlook.exe
    - acrobat.exe
    - acrord32.exe
    - iexplore.exe
    - opera.exe
    - firefox.exe
    - powershell.exe
  selection2:
    actor.process.file.name: java.exe
  selection3:
    actor.process.file.name|re: patch1-Hotfix1a
  selection4:
    actor.process.file.name: chrome.exe
  selection5:
    process.cmd_line: chrome-extension
  selection6:
    process.file.name: cmd.exe
  condition: ((selection1) or (selection2 and not selection3) or (selection4 and not selection5)) and selection6
how_to_implement: In order to successfully implement this analytic, you will need
  endpoint process data from a EDR product or Sysmon. This search has been modified
  to process raw sysmon data from attack_range's nxlogs on DSP.
known_false_positives: There are circumstances where an application may legitimately
  execute and interact with the Windows command-line interface.
references:
- https://attack.mitre.org/techniques/T1059/
tags:
  analytic_story:
  - Suspicious Command-Line Executions
  - Insider Threat
  asset_type: Endpoint
  confidence: 50
  impact: 70
  message: An instance of $parent_process_name$ spawning $process_name$ was identified
    on endpoint $dest_device_id$ by user $dest_user_id$, producing a suspicious event
    that warrants investigating.
  mitre_attack_id:
  - T1059
  observable: []
  product:
  - Splunk Behavioral Analytics
  required_fields: []
  kill_chain_phases:
  - Exploitation
  risk_score: 35
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1059.003/powershell_spawn_cmd/windows-security.log
    source: WinEventLog:Security
